---
require:
  - rubocop-rails
  - rubocop-performance
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2
  TargetRailsVersion: 7
  DisplayCopNames: true
  Exclude:
    - bin/**
    - db/schema.rb
    - db/migrate/**
    - db/data_schema.rb
    - vendor/**/*
    - node_modules/**/*
    - vendor/**/*
    - node_modules/**/*
    - tmp/**/*
  SuggestExtensions: false
Rails:
  Enabled: true
Style/ClassAndModuleChildren:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Rails/DynamicFindBy:
  Enabled: true
Rails/InverseOf:
  Enabled: false
