databases:
  - name: postgres
    ipAllowList: []
    databaseName: rails_project_65
    user: rails_project_65

services:
  - type: web
    name: rails_project_65
    env: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec rails s'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
